local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 10.0
  publish_frequency: 1
  static_map: false
  rolling_window: true
  max_obstacle_width: 2.0
  max_obstacle_height: 2.0
  width: 5
  height: 5
  resolution: 0.02

